import asyncio

from app.db.helpers import new_id, utcnow_iso
from app.db.repositories import insert_event, upsert_recommendation
from app.roles.orchestrator import Orchestrator
from app.services.portfolio import get_portfolio_summary


def make_recommendation(symbol: str = "NVDA") -> dict:
    return {
        "id": new_id("rec"),
        "symbol": symbol,
        "direction": None,
        "status": "observing",
        "strategy_type": "DEMO",
        "thesis": f"{symbol} event under review.",
        "entry_price": 110.0,
        "entry_logic": "test entry",
        "stop_price": 104.0,
        "stop_logic": "test stop",
        "target_price": 120.0,
        "target_logic": "test target",
        "position_size_shares": 100.0,
        "position_size_dollars": 11000.0,
        "time_horizon": "demo",
        "conviction": None,
        "supporting_roles": [],
        "blocking_risks": [],
        "created_at": utcnow_iso(),
        "updated_at": utcnow_iso(),
    }


def make_event(symbol: str = "NVDA") -> dict:
    return {
        "id": new_id("evt"),
        "type": "earnings",
        "symbol": symbol,
        "headline": f"{symbol} test event",
        "body_excerpt": "Generated by unit test.",
        "source": "test",
        "timestamp": utcnow_iso(),
        "importance": 5,
        "linked_recommendation_ids": [],
    }


def test_analyze_event_generates_role_conversation():
    orchestrator = Orchestrator()
    recommendation = make_recommendation()
    event = make_event()
    insert_event(event)
    upsert_recommendation(recommendation)

    analyzed = asyncio.run(orchestrator.analyze_event(recommendation, event, get_portfolio_summary()))
    timeline = orchestrator.timeline(recommendation["id"])

    assert analyzed["status"] == "awaiting_user_feedback"
    assert any(msg["sender"] == "role:trader" and msg["role"] != "trader" for msg in timeline)
    assert any(msg["role"] == "trader" for msg in timeline)


def test_group_chat_mention_routes_to_target_role():
    orchestrator = Orchestrator()
    recommendation = make_recommendation("AAPL")
    event = make_event("AAPL")
    insert_event(event)
    upsert_recommendation(recommendation)

    asyncio.run(orchestrator.route_group_chat(recommendation["id"], "@risk what worries you here?"))
    timeline = orchestrator.timeline(recommendation["id"])

    assert any(msg["role"] == "risk" for msg in timeline)
    assert not any(msg["sender"] == "role:trader" and msg["role"] == "risk" for msg in timeline)


def test_group_chat_records_directed_user_message():
    orchestrator = Orchestrator()
    recommendation = make_recommendation("MSFT")
    event = make_event("MSFT")
    insert_event(event)
    upsert_recommendation(recommendation)

    asyncio.run(orchestrator.route_group_chat(recommendation["id"], "@research what changed?"))
    timeline = orchestrator.timeline(recommendation["id"])

    assert any(
        msg["sender"] == "user"
        and msg["role"] == "research"
        and msg["structured_payload"].get("target_role") == "research"
        for msg in timeline
    )
